added colours and next step ;)

diff --git a/configure_others b/configure_others
--- a/configure_others
+++ b/configure_others
@@ -2,29 +2,44 @@
 
 PACKAGE_MANAGER="apt"
 
-command -v gcc   >/dev/null 2>&1 || { echo >&2 "gcc is being installed";   sudo ${PACKAGE_MANAGER} install build-essential; }
-command -v g++   >/dev/null 2>&1 || { echo >&2 "g++ is being installed";   sudo ${PACKAGE_MANAGER} install build-essential; }
-command -v flex  >/dev/null 2>&1 || { echo >&2 "flex is being installed";  sudo ${PACKAGE_MANAGER} install flex;            }
-command -v bison >/dev/null 2>&1 || { echo >&2 "bison is being installed"; sudo ${PACKAGE_MANAGER} install bison;           }
-command -v tree  >/dev/null 2>&1 || { echo >&2 "tree is being installed";  sudo ${PACKAGE_MANAGER} install tree;            }
+command -v gcc >/dev/null 2>&1 || {
+    echo -e >&2 "${YELLOW}gcc ${RED}is required but not found${NC}"
+    echo -e >&2 "${BLUE}... installing ${YELLOW}gcc${BLUE} ... ${NC}\n"
+    sudo ${PACKAGE_MANAGER} install build-essential
+    echo -e >&2 ""
+}
 
-CC=$(command -v gcc)
-CPP=$(command -v g++)
-FLEX=$(command -v flex)
-BISON=$(command -v bison)
-TREE=$(command -v tree)
+command -v g++ >/dev/null 2>&1 || {
+    echo -e >&2 "${YELLOW}g++ ${RED}is required but not found${NC}"
+    echo -e >&2 "${BLUE}... installing ${YELLOW}g++${BLUE} ... ${NC}\n"
+    echo >&2 "g++ is being installed"
+    sudo ${PACKAGE_MANAGER} install build-essential
+    echo -e >&2 ""
+}
 
-echo "gcc found at: ${CC}"
-echo "g++ found at: ${CPP}"
-echo "flex found at: ${FLEX}"
-echo "bison found at: ${BISON}"
-echo "tree found at: ${TREE}"
+command -v flex >/dev/null 2>&1 || {
+    echo -e >&2 "${YELLOW}flex ${RED}is required but not found${NC}"
+    echo -e >&2 "${BLUE}... installing ${YELLOW}flex${BLUE} ... ${NC}\n"
+    sudo ${PACKAGE_MANAGER} install flex
+    echo -e >&2 ""
+}
 
-echo -e "\
-CC := ${CC}\n\
-CPP := ${CPP}\n\
-FLEX := ${FLEX}\n\
-BISON := ${BISON}\n\
-TREE := ${TREE}\n\
-" > tools
+command -v bison >/dev/null 2>&1 || {
+    echo -e >&2 "${YELLOW}bison ${RED}is required but not found${NC}"
+    echo -e >&2 "${BLUE}... installing ${YELLOW}bison${BLUE} ... ${NC}\n"
+    sudo ${PACKAGE_MANAGER} install bison
+    echo -e >&2 ""
+}
 
+command -v tree >/dev/null 2>&1 || {
+    echo -e >&2 "${YELLOW}tree ${RED}is required but not found${NC}"
+    echo -e >&2 "${BLUE}... installing ${YELLOW}tree${BLUE} ... ${NC}\n"
+    sudo ${PACKAGE_MANAGER} install tree
+    echo -e >&2 ""
+}
+
+export CC=$(command -v gcc)
+export CPP=$(command -v g++)
+export FLEX=$(command -v flex)
+export BISON=$(command -v bison)
+export TREE=$(command -v tree)
